[theme]
base = "light"
primaryColor = "#0f2645"
backgroundColor = "#f5f3ef"
secondaryBackgroundColor = "#fdfcfa"
textColor = "#1a1714"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
