[theme]
base = "light"
primaryColor = "#3630a0"
backgroundColor = "#f0eeea"
secondaryBackgroundColor = "#ffffff"
textColor = "#18180f"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
